# Generated by Django 5.0.6 on 2024-07-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cppp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenderRefNum', models.IntegerField()),
                ('tenderID', models.CharField(max_length=50)),
                ('tenderName', models.CharField(max_length=50)),
                ('tenderCategory', models.CharField(max_length=50)),
                ('tenderFeeType', models.CharField(max_length=50)),
                ('tenderFee', models.IntegerField()),
                ('tenderValue', models.IntegerField()),
                ('emdType', models.CharField(max_length=50)),
                ('emd', models.IntegerField()),
                ('techBidOpeningDate', models.DateField()),
                ('finBidOpeningDate', models.DateField()),
                ('l1BidderName', models.CharField(max_length=50)),
                ('contractAwardDate', models.DateField()),
                ('l1BidderEmd', models.CharField(max_length=50)),
                ('l1BidderEmdValue', models.IntegerField()),
                ('l1BidderBg', models.CharField(max_length=50)),
                ('l1BidderBgValue', models.IntegerField()),
                ('paymentOptions', models.CharField(max_length=50)),
            ],
        ),
    ]
