# Generated by Django 5.0.6 on 2024-07-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemRefNum', models.IntegerField()),
                ('gemBidID', models.CharField(max_length=50)),
                ('gemName', models.CharField(max_length=50)),
                ('gemCategory', models.CharField(max_length=50)),
                ('gemFeeType', models.CharField(max_length=50)),
                ('gemFee', models.IntegerField()),
                ('gemValue', models.IntegerField()),
                ('emdType', models.CharField(max_length=50)),
                ('emd', models.IntegerField()),
                ('techBidOpeningDate', models.DateField()),
                ('finBidOpeningDate', models.DateField()),
                ('l1BidderName', models.CharField(max_length=50)),
                ('contractAwardDate', models.DateField()),
                ('l1BidderEmd', models.CharField(max_length=50)),
                ('l1BidderEmdValue', models.IntegerField()),
                ('l1BidderBg', models.CharField(max_length=50)),
                ('l1BidderBgValue', models.IntegerField()),
                ('paymentOptions', models.CharField(max_length=50)),
            ],
        ),
    ]
