# Generated by Django 5.0.6 on 2024-07-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIS', '0002_gem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cppp',
            name='emdType',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed', 'Fixed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cppp',
            name='l1BidderBg',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cppp',
            name='l1BidderEmd',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cppp',
            name='tenderCategory',
            field=models.CharField(choices=[('Goods', 'Goods'), ('Services', 'Services'), ('Works', 'Works')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cppp',
            name='tenderFeeType',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=50),
        ),
    ]
