# Generated by Django 5.0.6 on 2024-07-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIS', '0004_alter_cppp_paymentoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gem',
            name='emdType',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed', 'Fixed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gem',
            name='gemCategory',
            field=models.CharField(choices=[('Goods', 'Goods'), ('Services', 'Services')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gem',
            name='gemFeeType',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gem',
            name='l1BidderBg',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gem',
            name='l1BidderEmd',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gem',
            name='paymentOptions',
            field=models.CharField(choices=[('10%', '10%'), ('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('90%', '90%'), ('100%', '100%')], max_length=50),
        ),
    ]
