# Generated by Django 5.0.6 on 2024-07-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MIS', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
