# Generated by Django 5.0.6 on 2024-07-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MIS', '0008_userbase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='name',
            new_name='username',
        ),
    ]
