# Generated by Django 5.0.7 on 2024-07-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MIS', '0010_rename_tendername_cppp_tendertitle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cppp',
            old_name='finBidOpeningDate',
            new_name='financialBidOpeningDate',
        ),
        migrations.RenameField(
            model_name='cppp',
            old_name='techBidOpeningDate',
            new_name='technicalBidOpeningDate',
        ),
        migrations.RenameField(
            model_name='cppp',
            old_name='tenderRefNum',
            new_name='tenderReferenceNumber',
        ),
        migrations.RenameField(
            model_name='gem',
            old_name='finBidOpeningDate',
            new_name='financialBidOpeningDate',
        ),
        migrations.RenameField(
            model_name='gem',
            old_name='gemRefNum',
            new_name='gemReferenceNumber',
        ),
        migrations.RenameField(
            model_name='gem',
            old_name='techBidOpeningDate',
            new_name='technicalBidOpeningDate',
        ),
    ]
