# Generated by Django 5.0.7 on 2024-07-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIS', '0011_rename_finbidopeningdate_cppp_financialbidopeningdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenderReferenceNumber', models.IntegerField()),
                ('tenderID', models.CharField(max_length=50)),
                ('tenderTitle', models.CharField(max_length=50)),
                ('tenderCategory', models.CharField(choices=[('Goods', 'Goods'), ('Services', 'Services'), ('Works', 'Works')], max_length=50)),
                ('tenderFeeType', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=50)),
                ('tenderFee', models.IntegerField()),
                ('tenderValue', models.IntegerField()),
                ('emdType', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed', 'Fixed')], max_length=50)),
                ('emd', models.IntegerField()),
                ('technicalBidOpeningDate', models.DateField()),
                ('financialBidOpeningDate', models.DateField()),
                ('l1BidderName', models.CharField(max_length=50)),
                ('contractAwardDate', models.DateField()),
                ('l1BidderEmd', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=50)),
                ('l1BidderEmdValue', models.IntegerField()),
                ('l1BidderBg', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=50)),
                ('l1BidderBgValue', models.IntegerField()),
                ('paymentOptions', models.CharField(choices=[('10%', '10%'), ('25%', '25%'), ('50%', '50%'), ('75%', '75%'), ('90%', '90%'), ('100%', '100%')], max_length=50)),
            ],
        ),
    ]
